### ISSUE TITLE
text file data export issue: "signal height" chosen, however still MR based on area is exported!

### ISSUE THREAD

**Issue by Amsoht** [MrFuppes/IDL_IAU_DataProc#3]
I don't understand, where this comes from. The header says correctly `Eval_Mode: signal_height` and the file is named `28.15_SF6_h_iaudp.txt`. However, the data are exactly the same like when using the `signal_area`. When showing the Results Table in IAU DataProc, I get different data for the signal_height, which does make sense. Any ideas?

https://github.com/MrFuppes/IDL_IAU_DataProc/blob/c2b80bdc7115305aac6f502e4ebb53e8ffdd69d5/Report/dp_res2txt.pro#L28

**Comment by FObersteiner** [comment]
MR calculation is done [here](https://github.com/MrFuppes/IDL_IAU_DataProc/blob/c2b80bdc7115305aac6f502e4ebb53e8ffdd69d5/Tools_data/dp_calc_mrs.pro#L30); the case statement selects area or height respectively. Did you check if the keyword gets passed down to this point correctly?

Also, I think for `FUNCTION dp_calc_mrs`, *eval_mode* should be a parameter, not a keyword. IDL's function keywords don't take defaults so here, the implementation doesn't make much sense, what do you think?

I can look into this deeper tomorrow...

**Comment by Amsoht** [comment]
`eval_mode`is passed correctly to the function `dp_calc_mrs`. In the following lines it is set to 0 again:
https://github.com/MrFuppes/IDL_IAU_DataProc/blob/c2b80bdc7115305aac6f502e4ebb53e8ffdd69d5/Tools_data/dp_calc_mrs.pro#L17-L19
What was L19  originally supposed to do? I'd suggest to delete or comment out that line.

**Comment by FObersteiner** [comment]
should be fixed by https://github.com/MrFuppes/IDL_IAU_DataProc/commit/02fb843b7c93d3e29de95b7f3130b11bc25c94aa and https://github.com/MrFuppes/IDL_IAU_DataProc/commit/acf98b049bfbcec39f9c944e4e5e588923d99cd3

honestly, 5 years ago when I wrote this, I never properly tested "height eval" since I always used only area. I found a couple of other locations in the code (see second commit linked above), where it sticks to area eval mode, even if you have "height" selected on the widget.

**Comment by FObersteiner** [comment]
it's even simpler: [eval_mode determined in FUNC dp_calc_mrs](https://github.com/MrFuppes/IDL_IAU_DataProc/commit/528cbf598d15aa9fce50b4bacc078160c04a200f) - since dp_chrom is passed to the calc_mr function, I see no reason why parameter `eval_mode` cannot be extracted in-place!

**Comment by Amsoht** [comment]
> 
> 
> should be fixed by [02fb843](https://github.com/MrFuppes/IDL_IAU_DataProc/commit/02fb843b7c93d3e29de95b7f3130b11bc25c94aa) and [acf98b0](https://github.com/MrFuppes/IDL_IAU_DataProc/commit/acf98b049bfbcec39f9c944e4e5e588923d99cd3)
> 
> honestly, 5 years ago when I wrote this, I never properly tested "height eval" since I always used only area. I found a couple of other locations in the code (see second commit linked above), where it sticks to area eval mode, even if you have "height" selected on the widget.

I think that cancelled out before in those places, because `eval_mode` used to be extracted from `dp_chrom` when it hadn't been set as a keyword (see L18 in the code reference above). That's why showing the results table did indeed work, but exporting didn't. 

528cbf598d15aa9fce50b4bacc078160c04a200f should fix all of this, thank you!

**Comment by FObersteiner** [comment]
> I think that cancelled out before in those places, because `eval_mode` used to be extracted from `dp_chrom` when it hadn't been set as a keyword (see L18 in the code reference above). That's why showing the results table did indeed work, but exporting didn't.

exactly, but I think I didn't implement the keyword correctly so it just gave the right result for the wrong reason *sometimes*.

> [528cbf5](https://github.com/MrFuppes/IDL_IAU_DataProc/commit/528cbf598d15aa9fce50b4bacc078160c04a200f) should fix all of this, thank you!

I hope so. At the moment, I see no reason, why the eval_mode that is set in the dp_chrom data structure should be overridden by a keyword argument, so there's no reason for this keyword to exist.
